//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAT_BASIC
    {
        public PAT_BASIC()
        {
            this.PAT_RESULTH = new HashSet<PAT_RESULTH>();
        }
    
        public string HHISNUM { get; set; }
        public string HNAME { get; set; }
        public string HIDNO { get; set; }
        public string HSEX { get; set; }
        public string HBIRTHDT { get; set; }
        public string HBLDTYPE { get; set; }
        public string HPATADR { get; set; }
        public string HPMOBIL { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public string CREATEDATETIME { get; set; }
    
        public virtual ICollection<PAT_RESULTH> PAT_RESULTH { get; set; }
    }
}
