//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAT_RESULTD
    {
        public decimal PRD_TRX_NUM { get; set; }
        public string PRD_TEST_CODE { get; set; }
        public string PRD_TEST_NAME { get; set; }
        public string PRD_RESULT_VALUE { get; set; }
        public string PRD_RESULT_FLAG { get; set; }
        public string PRD_RANGE { get; set; }
        public string PRD_LINE_NO { get; set; }
        public string PRD_TRX_DT { get; set; }
        public decimal PRD_RESULT_LOLIMIT { get; set; }
        public decimal PRD_RESULT_UPLIMIT { get; set; }
    
        public virtual PAT_RESULTH PAT_RESULTH { get; set; }
    }
}
